services:
  hostify-backend:
    build: ./backend
    container_name: hostify-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./deployments:/deployments
      - ./nginx-proxy/conf.d:/nginx-conf
    environment:
      - HOSTIFY_DEPLOYMENTS_PATH=/deployments
      - HOSTIFY_NGINX_CONF_PATH=/nginx-conf
      - HOSTIFY_DOCKER_NETWORK=hostify_network
    networks:
      - hostify_network

  hostify-nginx-proxy:
    image: nginx:stable-alpine
    container_name: hostify-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - hostify_network

networks:
  hostify_network:
    name: hostify_network
    driver: bridge


