services:
  docklift-backend:
    build: ./backend
    container_name: docklift-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./deployments:/deployments
      - ./nginx-proxy/conf.d:/nginx-conf
    environment:
      - DOCKLIFT_DEPLOYMENTS_PATH=/deployments
      - DOCKLIFT_NGINX_CONF_PATH=/nginx-conf
      - DOCKLIFT_DOCKER_NETWORK=docklift_network
    networks:
      - docklift_network

  docklift-nginx-proxy:
    image: nginx:stable-alpine
    container_name: docklift-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - docklift_network

networks:
  docklift_network:
    name: docklift_network
    driver: bridge


